### ISSUE TITLE
Make it work in node-js

### ISSUE THREAD

**Issue by reiner-dolp** [reiner-dolp/liblouis-js#10]
- [x] Resolve #8 
- [ ] Modify `liblouis.enableOnDemandTableLoading`
- [x] Add exports and imports

**Comment by frastlin** [comment]
The first thing is to [specify the liblouis.js file](https://github.com/reiner-dolp/liblouis-js/issues/8)
Next is to figure out how easy_wrapper and the liblouis.js file will work together.
Currently there is a bug in the easy_wrapper that says "FS is not defined" on line 21.
Then for exports, I think there should be an index.js file just for NodeJS. this would require the easy_wrapper and the liblouis file. It would export the functions in easy_wrapper and create access to the C API.
It could also have the table search functionality as I think table loading is different in browsers than in node. In node one uses fs and in the browser I think there are three options, either having the tables in the file, through an url that points to a folder on a server or by loading assets when the page loads.
The liblouis file seems to already check for the environment and has code accordingly.
Another option is to require browserify for client side scripting and then the syntax will be the same for node and for the browser.

**Comment by reiner-dolp** [comment]
There is no bug in in `easy_wrapper.js`. You have to include one of the liblouis builds first.

**Comment by frastlin** [comment]
I spent some time looking through the code and testing and it seems as if the liblouis-no-tables module is already built for NodeJS. It is just the wrapper module that needs reworking.
Some questions:
Where is the table information stored so liblouis can access it? I'm not 100% sure what all the FS functions are doing, but FS.lookup seems to be where the table is stored, but FS is not in the Module namespace for NodeJS.

Otherwise, I think everything else can almost be used without modification.

**Comment by reiner-dolp** [comment]
the files `liblouis-(...)` are not written by hand but created by cross compiling the original C source code  located at https://github.com/liblouis/liblouis using the program emscripten. Emscripten has extensive documentation. The `FS` module is documented at https://kripken.github.io/emscripten-site/docs/api_reference/Filesystem-API.html.

The easiest way to make it work in node-js is by adding a file liblouis.js that simply imports and reexports  both the original file and the easy wrapper. Easy wrapper should use some variation of the module pattern to correctly export itself in each execution environment:

```js
(function ( root, factory ) {
    if ( typeof exports === 'object' ) {
        // CommonJS
        factory( exports, require('b') );
    } else if ( typeof define === 'function' && define.amd ) {
        // AMD. Register as an anonymous module.
        define( ['exports', 'b'], factory);
    } else {
        // Browser globals
        factory( (root.commonJsStrict = {}), root.b );
    }
}(this, function ( exports, b ) {
    //use b in some fashion.
 
    // attach properties to the exports object to define
    // the exported module properties.
    exports.action = function () {};
}));
```
(snippet taken from: https://addyosmani.com/resources/essentialjsdesignpatterns/book/)

That should be enough to make the package work.

**Comment by reiner-dolp** [comment]
Initial node js support was just added in commit 75cd8a2.
