### ISSUE TITLE
Creating an NPM package or giving directions on how to setup the package structure without NPM?

### ISSUE THREAD

**Issue by frastlin** [reiner-dolp/liblouis-js#6]
Hello,
I am wondering if this could please be added to [NPM?](https://www.npmjs.com/)
I can't seem to figure out what liblouis.js is supposed to be when there is no liblouis.js file.
I would love to either have an npm package or directions on how to setup the package so I can:
require("liblouis-js")
in my project.
Thanks,

**Comment by reiner-dolp** [comment]
Hi,

thanks for your interest in this package.

This repository _is_ a npm package. It is just not published in the npm package registry. Installation instructions can be found on [stackoverflow](http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly) or in the official docs on [install](https://docs.npmjs.com/cli/install), resp. [package files](https://docs.npmjs.com/files/package.json).

Note, that I wrote this package for browser environments. Running it with node-js might require some modification. Please open a bug report or pull request stating issues you had to resolve for node-js environments.

As a result of your I opened up several issues: #8 #7 #9.
