### ISSUE TITLE
main file "liblouis.js" in "package.json" does not exist

### ISSUE THREAD

**Issue by reiner-dolp** [reiner-dolp/liblouis-js#8]
However, what should be the default?

**Comment by frastlin** [comment]
I think that the easy_wrapper module should be the main module with a function like liblouis-js.ccall("lou_version", "string") to access the c api.
The without tables should be the only module. The table search should look in the app dir first, then look in the libouis-js module second.
The tables included should be either an extra download or created with a function like liblouis-js.create_single_file(tables=[], name="liblouis-js_with_tables.js")
then have a single file with the included tables created in the current dir.
I think the included tables file is only good for browser usage and not node usage.
Thanks,

**Comment by reiner-dolp** [comment]
I would be happy to review a pull request that adds node-js support. However, support of browser environments has priority and should work without a build step.

**Comment by reiner-dolp** [comment]
Resolved by commit 75cd8a2.
